begin;

-- The browser can only call the two RPC functions granted at the bottom.
-- Direct table access stays closed even if a future Supabase default changes.
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public, anon, authenticated, service_role;

create table public.app_data_seeds (
  seed_key text primary key,
  applied_at timestamptz not null default now()
);

create table public.app_users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text not null default '',
  role text not null default 'parent' check (role in ('admin','parent','match_registrar')),
  active boolean not null default true,
  account_user_id uuid unique references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create unique index app_users_email_unique on public.app_users (lower(email)) where email is not null and email <> '';
create unique index app_users_phone_unique on public.app_users ((regexp_replace(phone, '\D', '', 'g'))) where phone <> '';

create table public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  jersey_number integer,
  shirt_size text not null default '',
  shorts_size text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.trainings (
  id bigint generated by default as identity primary key,
  date date not null,
  start_time text not null default '',
  duration_minutes integer not null default 60 check (duration_minutes > 0),
  title text not null default 'Lagstrening',
  theme text not null default '',
  plan text not null default '',
  notes text not null default '',
  status text not null default 'planned' check (status in ('planned','completed','cancelled')),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.training_attendance (
  training_id bigint not null references public.trainings(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  primary key (training_id, player_id)
);

create table public.exercises (
  id bigint generated by default as identity primary key,
  seed_key text unique,
  title text not null,
  category text not null check (category in ('warmup','defense','attack','cardio','strength')),
  description text not null default '',
  duration_minutes integer not null default 10 check (duration_minutes > 0),
  equipment text not null default '',
  source_title text not null default '',
  source_url text not null default '',
  created_at timestamptz not null default now()
);

create table public.training_exercises (
  id bigint generated by default as identity primary key,
  training_id bigint not null references public.trainings(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  section text not null check (section in ('warmup','technique','match')),
  sort_order integer not null default 0,
  duration_minutes integer not null default 10 check (duration_minutes > 0),
  notes text not null default ''
);

create table public.matches (
  id bigint generated by default as identity primary key,
  date date not null,
  start_time text not null default '',
  opponent text not null,
  team text not null default 'Stokmarknes',
  home_away text not null default 'home' check (home_away in ('home','away')),
  competition text not null default 'Serie',
  match_type text not null default 'league' check (match_type in ('league','cup','friendly')),
  cup_name text not null default '',
  venue text not null default '',
  our_score integer,
  opponent_score integer,
  period_count integer not null default 2,
  period_minutes integer not null default 20 check (period_minutes between 1 and 60),
  match_phase text not null default 'pre_match' check (match_phase in ('pre_match','first_half','halftime','second_half','completed')),
  current_period integer not null default 0,
  period_elapsed_seconds integer not null default 0,
  clock_started_at timestamptz,
  elapsed_seconds integer not null default 0,
  clock_running boolean not null default false,
  notes text not null default '',
  status text not null default 'planned' check (status in ('planned','live','completed','cancelled')),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.match_players (
  match_id bigint not null references public.matches(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  starter boolean not null default false,
  goalkeeper boolean not null default false,
  captain boolean not null default false,
  position text not null default 'bench' check (position in ('goalkeeper','right_wing','right_back','center','left_back','left_wing','bench')),
  primary key (match_id, player_id)
);

create table public.match_events (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  player_id bigint references public.players(id) on delete cascade,
  side text not null default 'ours' check (side in ('ours','opponent')),
  type text not null check (type in ('goal_open','goal_penalty','penalty_miss','yellow','two_min','red','save_open','save_penalty')),
  match_second integer not null default 0,
  period integer not null default 1,
  period_second integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.match_substitutions (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  player_in_id bigint not null references public.players(id) on delete cascade,
  player_out_id bigint not null references public.players(id) on delete cascade,
  position text not null check (position in ('goalkeeper','right_wing','right_back','center','left_back','left_wing')),
  match_second integer not null default 0,
  period integer not null default 1,
  period_second integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.match_registrars (
  match_id bigint not null references public.matches(id) on delete cascade,
  user_id bigint not null references public.app_users(id) on delete cascade,
  primary key (match_id, user_id)
);

create index trainings_date_idx on public.trainings(date desc);
create index matches_date_idx on public.matches(date, start_time);
create index match_events_match_idx on public.match_events(match_id, id desc);
create index match_substitutions_match_idx on public.match_substitutions(match_id, id);
create index match_registrars_user_idx on public.match_registrars(user_id, match_id);

do $$ declare t text; begin
  foreach t in array array['app_data_seeds','app_users','players','trainings','training_attendance','exercises','training_exercises','matches','match_players','match_events','match_substitutions','match_registrars'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from public, anon, authenticated', t);
  end loop;
end $$;

create or replace function public.claim_app_user()
returns public.app_users
language plpgsql security definer set search_path = ''
as $$
declare
  uid uuid := auth.uid();
  jwt jsonb := auth.jwt();
  mail text := lower(coalesce(jwt->>'email',''));
  phone_digits text := regexp_replace(coalesce(jwt->>'phone',''), '\D', '', 'g');
  result public.app_users;
begin
  if uid is null then raise exception 'Logg inn for å fortsette.' using errcode = '28000'; end if;
  select * into result from public.app_users where account_user_id = uid and active limit 1;
  if found then return result; end if;
  update public.app_users
     set account_user_id = uid
   where id = (
     select id from public.app_users
      where active and account_user_id is null
        and ((mail <> '' and lower(coalesce(email,'')) = mail)
          or (phone_digits <> '' and regexp_replace(phone, '\D', '', 'g') = phone_digits))
      order by id limit 1
   )
  returning * into result;
  if result.id is null then raise exception 'Brukeren er ikke forhåndsgodkjent.' using errcode = '42501'; end if;
  return result;
end;
$$;

create or replace function public.season_snapshot()
returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
  u public.app_users := public.claim_app_user();
  match_ids bigint[];
begin
  if u.role = 'match_registrar' then
    select coalesce(array_agg(match_id), array[]::bigint[]) into match_ids from public.match_registrars where user_id = u.id;
  else
    select coalesce(array_agg(id), array[]::bigint[]) into match_ids from public.matches;
  end if;

  return jsonb_build_object(
    'players', case when u.role = 'admin' then
      (select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'jerseyNumber',jersey_number,'shirtSize',shirt_size,'shortsSize',shorts_size,'active',active,'createdAt',created_at) order by active desc, jersey_number, name),'[]') from public.players)
      else (select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'jerseyNumber',jersey_number,'shirtSize','','shortsSize','','active',active,'createdAt',created_at) order by active desc, jersey_number, name),'[]') from public.players) end,
    'trainings', case when u.role='admin' then (select coalesce(jsonb_agg(jsonb_build_object('id',id,'date',date,'startTime',start_time,'durationMinutes',duration_minutes,'title',title,'theme',theme,'plan',plan,'notes',notes,'status',status,'completedAt',completed_at,'createdAt',created_at) order by date desc,start_time desc),'[]') from public.trainings) else '[]'::jsonb end,
    'attendance', case when u.role='admin' then (select coalesce(jsonb_agg(jsonb_build_object('trainingId',training_id,'playerId',player_id)),'[]') from public.training_attendance) else '[]'::jsonb end,
    'exercises', case when u.role='admin' then (select coalesce(jsonb_agg(jsonb_build_object('id',id,'seedKey',seed_key,'title',title,'category',category,'description',description,'durationMinutes',duration_minutes,'equipment',equipment,'sourceTitle',source_title,'sourceUrl',source_url,'createdAt',created_at) order by category,title),'[]') from public.exercises) else '[]'::jsonb end,
    'trainingExercises', case when u.role='admin' then (select coalesce(jsonb_agg(jsonb_build_object('id',id,'trainingId',training_id,'exerciseId',exercise_id,'section',section,'sortOrder',sort_order,'durationMinutes',duration_minutes,'notes',notes) order by training_id,section,sort_order,id),'[]') from public.training_exercises) else '[]'::jsonb end,
    'matches', (select coalesce(jsonb_agg(jsonb_build_object('id',id,'date',date,'startTime',start_time,'opponent',opponent,'team',team,'homeAway',home_away,'competition',competition,'matchType',match_type,'cupName',cup_name,'venue',venue,'ourScore',our_score,'opponentScore',opponent_score,'periodCount',period_count,'periodMinutes',period_minutes,'matchPhase',match_phase,'currentPeriod',current_period,'periodElapsedSeconds',period_elapsed_seconds,'clockStartedAt',clock_started_at,'elapsedSeconds',elapsed_seconds,'clockRunning',clock_running,'notes',case when u.role='parent' then '' else notes end,'status',status,'completedAt',completed_at,'createdAt',created_at) order by date,start_time),'[]') from public.matches where id=any(match_ids)),
    'matchPlayers', (select coalesce(jsonb_agg(jsonb_build_object('matchId',match_id,'playerId',player_id,'starter',starter,'goalkeeper',goalkeeper,'captain',captain,'position',position)),'[]') from public.match_players where match_id=any(match_ids)),
    'matchEvents', case when u.role<>'parent' then (select coalesce(jsonb_agg(jsonb_build_object('id',id,'matchId',match_id,'playerId',player_id,'side',side,'type',type,'matchSecond',match_second,'period',period,'periodSecond',period_second,'createdAt',created_at) order by id desc),'[]') from public.match_events where match_id=any(match_ids)) else '[]'::jsonb end,
    'matchSubstitutions', case when u.role<>'parent' then (select coalesce(jsonb_agg(jsonb_build_object('id',id,'matchId',match_id,'playerInId',player_in_id,'playerOutId',player_out_id,'position',position,'matchSecond',match_second,'period',period,'periodSecond',period_second,'createdAt',created_at) order by id),'[]') from public.match_substitutions where match_id=any(match_ids)) else '[]'::jsonb end,
    'appUsers', case when u.role='admin' then (select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'email',email,'phone',phone,'role',role,'active',active,'accountUserId',account_user_id,'createdAt',created_at) order by role,name),'[]') from public.app_users) else '[]'::jsonb end,
    'matchRegistrars', case when u.role='admin' then (select coalesce(jsonb_agg(jsonb_build_object('matchId',match_id,'userId',user_id)),'[]') from public.match_registrars) else '[]'::jsonb end,
    'currentUser', jsonb_build_object('id',u.id,'name',u.name,'email',u.email,'role',u.role),
    'cloudStorage', jsonb_build_object('provider','Supabase','configured',true,'mode','prepared')
  );
end;
$$;

revoke all on function public.claim_app_user() from public, anon;
revoke all on function public.season_snapshot() from public, anon;
grant execute on function public.claim_app_user() to authenticated;
grant execute on function public.season_snapshot() to authenticated;

commit;
