create table public.cups (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date not null,
  end_date date not null,
  venue text not null default '',
  period_minutes integer not null default 18 check (period_minutes between 1 and 60),
  created_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create unique index cups_name_start_unique on public.cups (lower(name), start_date);

create table public.cup_teams (
  id bigint generated by default as identity primary key,
  cup_id bigint not null references public.cups(id) on delete cascade,
  name text not null,
  sort_order integer not null default 1 check (sort_order > 0),
  unique (cup_id, name),
  unique (cup_id, id)
);

create table public.cup_team_players (
  cup_id bigint not null,
  cup_team_id bigint not null,
  player_id bigint not null references public.players(id) on delete cascade,
  primary key (cup_id, player_id),
  foreign key (cup_id, cup_team_id) references public.cup_teams(cup_id, id) on delete cascade
);
create index cup_team_players_team_idx on public.cup_team_players(cup_team_id);
create index cup_team_players_cup_team_idx on public.cup_team_players(cup_id,cup_team_id);
create index cup_team_players_player_idx on public.cup_team_players(player_id);

create table public.player_guardians (
  player_id bigint not null references public.players(id) on delete cascade,
  user_id bigint not null references public.app_users(id) on delete cascade,
  primary key (player_id, user_id)
);
create index player_guardians_user_idx on public.player_guardians(user_id);

alter table public.matches add column cup_id bigint;
alter table public.matches add column cup_team_id bigint;
alter table public.matches add constraint matches_cup_team_fk
  foreign key (cup_id, cup_team_id) references public.cup_teams(cup_id, id) on delete cascade;

alter table public.cups enable row level security;
alter table public.cup_teams enable row level security;
alter table public.cup_team_players enable row level security;
alter table public.player_guardians enable row level security;
revoke all on public.cups, public.cup_teams, public.cup_team_players, public.player_guardians from public, anon, authenticated;

insert into public.player_guardians(player_id,user_id)
select p.id,u.id from (values
  ('Alina Martinsen','veronica_nordrum@hotmail.com'),
  ('Alina Martinsen','alexander.marti95@hotmail.no'),
  ('Astrid Johanne Hansen','isabelldreyer@hotmail.com'),
  ('Astrid Johanne Hansen','ivanhansen1985@hotmail.com'),
  ('Hanna Olsen','skymo30@yahoo.com.ph'),
  ('Helene Larssen','dag-h-larssen@hotmail.com'),
  ('Helene Larssen','tuttsia@hotmail.com'),
  ('Hodan Ismail','riyaan-10@hotmail.com'),
  ('Julia Eilertsen','joakiell@gmail.com'),
  ('Julia Eilertsen','kaja.munoz@hotmail.com'),
  ('Maja Welde','loneanita88@gmail.com'),
  ('Maja Welde','weldesen@hotmail.com'),
  ('Martine Eilertsen','joakiell@gmail.com'),
  ('Martine Eilertsen','kaja.munoz@hotmail.com'),
  ('Martine Sørensen','bene_roenning@hotmail.com'),
  ('Martine Sørensen','jonas@krtransport.no'),
  ('Mathea Berg','stineberg85@gmail.com'),
  ('Milana Khylko','oksanavasyuk00@gmail.com'),
  ('Ragnhild Sofie Dahl','tonje.skinstad@live.no'),
  ('Ragnhild Sofie Dahl','morten@vkbb.no'),
  ('Sara Ellingsen','maria.antonsen@hotmail.com'),
  ('Sara Ellingsen','espenellingsen@outlook.com'),
  ('Sophia Larssen','ingvildwlarsen@gmail.com'),
  ('Sophia Larssen','mariusnilsen50@gmail.com'),
  ('Terese Jakuboviciute','s.vainauskaite@yahoo.com'),
  ('Terese Jakuboviciute','tomasjakubovicius@gmail.com')
) as links(player_name,email)
join public.players p on lower(p.name)=lower(links.player_name)
join public.app_users u on lower(u.email)=lower(links.email);

create or replace function public.cup_snapshot()
returns jsonb language plpgsql security definer set search_path=''
as $$
declare u public.app_users := public.claim_app_user();
begin
  return jsonb_build_object(
    'cups',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'startDate',start_date,'endDate',end_date,'venue',venue,'periodMinutes',period_minutes,'createdAt',created_at) order by start_date,name),'[]') from public.cups),
    'cupTeams',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'cupId',cup_id,'name',name,'sortOrder',sort_order) order by cup_id,sort_order,id),'[]') from public.cup_teams),
    'cupTeamPlayers',(select coalesce(jsonb_agg(jsonb_build_object('cupId',cup_id,'cupTeamId',cup_team_id,'playerId',player_id) order by cup_id,cup_team_id,player_id),'[]') from public.cup_team_players),
    'playerGuardians',case when u.role='admin' then (select coalesce(jsonb_agg(jsonb_build_object('playerId',player_id,'userId',user_id) order by player_id,user_id),'[]') from public.player_guardians) else '[]'::jsonb end,
    'cupMatchLinks',(select coalesce(jsonb_agg(jsonb_build_object('matchId',id,'cupId',cup_id,'cupTeamId',cup_team_id) order by cup_id,date,start_time,id),'[]') from public.matches where cup_id is not null)
  );
end;
$$;

create or replace function public.cup_action(payload jsonb)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare
  u public.app_users := public.claim_app_user();
  a text := coalesce(payload->>'action','');
  cid bigint := nullif(payload->>'cupId','')::bigint;
  ctid bigint := nullif(payload->>'cupTeamId','')::bigint;
  mid bigint;
  registrar_id bigint := nullif(payload->>'registrarUserId','')::bigint;
  team_count integer;
  current_count integer;
  item jsonb;
  cup_row public.cups;
  team_row public.cup_teams;
  pos text;
begin
  perform public.require_admin(u);
  if a='saveCup' then
    if btrim(coalesce(payload->>'name',''))='' or nullif(payload->>'startDate','') is null or nullif(payload->>'endDate','') is null then raise exception 'Navn og dato må fylles ut.'; end if;
    team_count := least(6,greatest(1,coalesce((payload->>'teamCount')::integer,1)));
    if cid is null then
      insert into public.cups(name,start_date,end_date,venue,period_minutes)
      values(btrim(payload->>'name'),(payload->>'startDate')::date,(payload->>'endDate')::date,btrim(coalesce(payload->>'venue','')),least(60,greatest(1,coalesce((payload->>'periodMinutes')::integer,18)))) returning id into cid;
    else
      update public.cups set name=btrim(payload->>'name'),start_date=(payload->>'startDate')::date,end_date=(payload->>'endDate')::date,venue=btrim(coalesce(payload->>'venue','')),period_minutes=least(60,greatest(1,coalesce((payload->>'periodMinutes')::integer,18))) where id=cid;
      if not found then raise exception 'Cupen finnes ikke.'; end if;
    end if;
    select count(*) into current_count from public.cup_teams where cup_id=cid;
    if team_count > current_count then
      for current_count in current_count+1..team_count loop insert into public.cup_teams(cup_id,name,sort_order) values(cid,case when team_count=1 then 'STHK' else 'STHK '||current_count end,current_count); end loop;
    elsif team_count < current_count then
      if exists(select 1 from public.matches m join public.cup_teams t on t.id=m.cup_team_id where t.cup_id=cid and t.sort_order>team_count) then raise exception 'Fjern kampene til laget før du reduserer antall lag.'; end if;
      delete from public.cup_teams where cup_id=cid and sort_order>team_count;
    end if;
    if team_count>1 then update public.cup_teams set name='STHK '||sort_order where cup_id=cid; else update public.cup_teams set name='STHK' where cup_id=cid; end if;
    return jsonb_build_object('id',cid);
  elsif a='saveCupRosters' then
    if cid is null or not exists(select 1 from public.cups where id=cid) then raise exception 'Cupen finnes ikke.'; end if;
    delete from public.cup_team_players where cup_id=cid;
    for item in select value from jsonb_array_elements(coalesce(payload->'assignments','[]')) loop
      ctid:=nullif(item->>'cupTeamId','')::bigint;
      if not exists(select 1 from public.cup_teams where id=ctid and cup_id=cid) then raise exception 'Et valgt lag tilhører ikke cupen.'; end if;
      if not exists(select 1 from public.players where id=(item->>'playerId')::bigint and active) then raise exception 'En valgt spiller finnes ikke eller er deaktivert.'; end if;
      insert into public.cup_team_players values(cid,ctid,(item->>'playerId')::bigint);
    end loop;
    return '{"ok":true}';
  elsif a='saveCupMatch' then
    select * into cup_row from public.cups where id=cid;
    select * into team_row from public.cup_teams where id=ctid and cup_id=cid;
    if cup_row.id is null or team_row.id is null then raise exception 'Velg cup og lag.'; end if;
    if btrim(coalesce(payload->>'date',''))='' or btrim(coalesce(payload->>'opponent',''))='' then raise exception 'Dato og motstander må fylles ut.'; end if;
    if registrar_id is not null and not exists(select 1 from public.app_users au join public.player_guardians pg on pg.user_id=au.id join public.cup_team_players ctp on ctp.player_id=pg.player_id and ctp.cup_id=cid and ctp.cup_team_id=ctid where au.id=registrar_id and au.active and au.role='parent') then raise exception 'Kampregistratoren må være foresatt til en spiller på laget.'; end if;
    insert into public.matches(date,start_time,opponent,team,home_away,competition,match_type,cup_name,venue,period_count,period_minutes,notes,cup_id,cup_team_id)
    values((payload->>'date')::date,btrim(coalesce(payload->>'startTime','')),btrim(payload->>'opponent'),team_row.name,case when payload->>'homeAway'='away' then 'away' else 'home' end,cup_row.name,'cup',cup_row.name,coalesce(nullif(btrim(coalesce(payload->>'venue','')),''),cup_row.venue),2,cup_row.period_minutes,btrim(coalesce(payload->>'notes','')),cid,ctid) returning id into mid;
    for item in select value from jsonb_array_elements(coalesce(payload->'roster','[]')) loop
      if not exists(select 1 from public.cup_team_players where cup_id=cid and cup_team_id=ctid and player_id=(item->>'playerId')::bigint) then raise exception 'Laguttaket inneholder en spiller som ikke er på cuplaget.'; end if;
      pos:=case when coalesce(item->>'position','') in ('goalkeeper','right_wing','right_back','center','left_back','left_wing','bench') then item->>'position' else 'bench' end;
      insert into public.match_players(match_id,player_id,starter,goalkeeper,captain,position) values(mid,(item->>'playerId')::bigint,pos<>'bench',pos='goalkeeper',coalesce((item->>'captain')::boolean,false),pos);
    end loop;
    update public.match_players set captain=false where match_id=mid and captain and player_id<>(select min(player_id) from public.match_players where match_id=mid and captain);
    if registrar_id is not null then insert into public.match_registrars values(mid,registrar_id); end if;
    return jsonb_build_object('id',mid);
  elsif a='deleteCup' then
    if cid is null or not exists(select 1 from public.cups where id=cid) then raise exception 'Cupen finnes ikke.'; end if;
    delete from public.cups where id=cid;
    return '{"ok":true}';
  end if;
  raise exception 'Ukjent cuphandling.';
end;
$$;

revoke all on function public.cup_snapshot() from public, anon;
revoke all on function public.cup_action(jsonb) from public, anon;
grant execute on function public.cup_snapshot() to authenticated;
grant execute on function public.cup_action(jsonb) to authenticated;
