begin;

alter table public.match_events
  add column if not exists annulled boolean not null default false,
  add column if not exists annulled_at timestamptz,
  add column if not exists annulled_by bigint references public.app_users(id) on delete set null;

alter table public.match_substitutions
  add column if not exists swap boolean not null default false,
  add column if not exists player_in_previous_position text
    check (player_in_previous_position in ('goalkeeper','right_wing','right_back','center','left_back','left_wing'));

create table if not exists public.match_comments (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  author_user_id bigint not null references public.app_users(id) on delete cascade,
  visibility text not null check (visibility in ('public','internal')),
  body text not null check (char_length(btrim(body)) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists match_comments_match_idx on public.match_comments(match_id, created_at desc);
alter table public.match_comments enable row level security;
revoke all on table public.match_comments from public, anon, authenticated;
revoke usage, select on sequence public.match_comments_id_seq from public, anon, authenticated;

create or replace function public.recompute_match_score(target_match bigint)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare ours integer; theirs integer;
begin
  select count(*) filter(where side='ours' and type in ('goal_open','goal_penalty') and not annulled),
         count(*) filter(where side='opponent' and type in ('goal_open','goal_penalty') and not annulled)
    into ours,theirs from public.match_events where match_id=target_match;
  update public.matches set our_score=ours, opponent_score=theirs where id=target_match;
  return jsonb_build_object('ourScore',ours,'opponentScore',theirs);
end $$;

create or replace function public.match_enhancements_snapshot(match_id_input bigint default null)
returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
  u public.app_users := public.claim_app_user();
begin
  if match_id_input is not null and not exists(select 1 from public.matches where id=match_id_input) then
    raise exception 'Kampen finnes ikke.';
  end if;

  return jsonb_build_object(
    'matchEvents', (select coalesce(jsonb_agg(jsonb_build_object(
      'id',e.id,'matchId',e.match_id,'playerId',e.player_id,'side',e.side,'type',e.type,
      'matchSecond',e.match_second,'period',e.period,'periodSecond',e.period_second,
      'annulled',e.annulled,'annulledAt',e.annulled_at,'createdAt',e.created_at
    ) order by e.id desc),'[]'::jsonb) from public.match_events e
      where match_id_input is null or e.match_id=match_id_input),
    'matchSubstitutions', (select coalesce(jsonb_agg(jsonb_build_object(
      'id',s.id,'matchId',s.match_id,'playerInId',s.player_in_id,'playerOutId',s.player_out_id,
      'position',s.position,'swap',s.swap,'playerInPreviousPosition',s.player_in_previous_position,
      'matchSecond',s.match_second,'period',s.period,'periodSecond',s.period_second,'createdAt',s.created_at
    ) order by s.id),'[]'::jsonb) from public.match_substitutions s
      where match_id_input is null or s.match_id=match_id_input),
    'matchComments', (select coalesce(jsonb_agg(jsonb_build_object(
      'id',c.id,'matchId',c.match_id,'visibility',c.visibility,'body',c.body,
      'authorName',au.name,'createdAt',c.created_at
    ) order by c.created_at desc,c.id desc),'[]'::jsonb)
      from public.match_comments c join public.app_users au on au.id=c.author_user_id
      where (match_id_input is null or c.match_id=match_id_input)
        and (c.visibility='public' or u.role='admin' or exists(
          select 1 from public.match_registrars mr where mr.match_id=c.match_id and mr.user_id=u.id
        )))
  );
end $$;

create or replace function public.match_enhancement_action(payload jsonb)
returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
  u public.app_users := public.claim_app_user();
  a text := coalesce(payload->>'action','');
  mid bigint;
  eid bigint;
  rid bigint;
  incoming bigint;
  outgoing bigint;
  m public.matches;
  item jsonb;
  current_positions jsonb := '{}'::jsonb;
  outgoing_position text;
  incoming_position text;
  period_limit integer;
  visibility_value text;
  comment_body text;
  score jsonb;
begin
  if a='setEventAnnulled' then
    eid := (payload->>'eventId')::bigint;
    select match_id into mid from public.match_events where id=eid and type in ('goal_open','goal_penalty');
    if mid is null then raise exception 'Målet finnes ikke.'; end if;
    perform public.require_editable_match(u,mid);
    update public.match_events
      set annulled=coalesce((payload->>'annulled')::boolean,true),
          annulled_at=case when coalesce((payload->>'annulled')::boolean,true) then now() else null end,
          annulled_by=case when coalesce((payload->>'annulled')::boolean,true) then u.id else null end
      where id=eid;
    score:=public.recompute_match_score(mid);
    return jsonb_build_object('ok',true,'score',score);

  elsif a='swapKeeper' then
    mid:=(payload->>'matchId')::bigint;
    outgoing:=(payload->>'goalkeeperId')::bigint;
    incoming:=(payload->>'playerId')::bigint;
    m:=public.require_editable_match(u,mid);
    if incoming=outgoing or not exists(select 1 from public.match_players where match_id=mid and player_id=incoming)
      or not exists(select 1 from public.match_players where match_id=mid and player_id=outgoing) then
      raise exception 'Begge spillerne må være med i laguttaket.';
    end if;
    select coalesce(jsonb_object_agg(player_id::text,position),'{}') into current_positions
      from public.match_players where match_id=mid;
    for item in select jsonb_build_object('in',player_in_id,'out',player_out_id,'position',position,
        'swap',swap,'previous',player_in_previous_position)
      from public.match_substitutions where match_id=mid order by id loop
      if coalesce((item->>'swap')::boolean,false) then
        current_positions:=jsonb_set(current_positions,array[item->>'out'],to_jsonb(item->>'previous'));
      else
        current_positions:=jsonb_set(current_positions,array[item->>'out'],to_jsonb('bench'::text));
      end if;
      current_positions:=jsonb_set(current_positions,array[item->>'in'],to_jsonb(item->>'position'));
    end loop;
    outgoing_position:=current_positions->>outgoing::text;
    incoming_position:=current_positions->>incoming::text;
    if outgoing_position<>'goalkeeper' then raise exception 'Den valgte spilleren står ikke i mål.'; end if;
    if incoming_position not in ('right_wing','right_back','center','left_back','left_wing') then
      raise exception 'Velg en utespiller som allerede er på banen.';
    end if;
    if exists(select 1 from public.match_events where match_id=mid and player_id=incoming and side='ours' and type='red') then
      raise exception 'En spiller med rødt kort kan ikke settes i mål.';
    end if;
    period_limit:=greatest(60,m.period_minutes*60);
    insert into public.match_substitutions(match_id,player_in_id,player_out_id,position,swap,player_in_previous_position,match_second,period,period_second)
    values(mid,incoming,outgoing,'goalkeeper',true,incoming_position,
      greatest(0,coalesce((payload->>'matchSecond')::integer,0)),case when m.current_period=2 then 2 else 1 end,
      least(period_limit,greatest(0,coalesce((payload->>'periodSecond')::integer,coalesce((payload->>'matchSecond')::integer,0)))))
    returning id into rid;
    return jsonb_build_object('substitution',jsonb_build_object('id',rid));

  elsif a='addMatchComment' then
    mid:=(payload->>'matchId')::bigint;
    perform public.require_editable_match(u,mid);
    visibility_value:=case when payload->>'visibility'='internal' then 'internal' else 'public' end;
    comment_body:=btrim(coalesce(payload->>'body',''));
    if comment_body='' or char_length(comment_body)>1000 then raise exception 'Kommentaren må inneholde mellom 1 og 1000 tegn.'; end if;
    insert into public.match_comments(match_id,author_user_id,visibility,body)
      values(mid,u.id,visibility_value,comment_body) returning id into rid;
    return jsonb_build_object('comment',jsonb_build_object('id',rid));

  elsif a='deleteMatchComment' then
    rid:=(payload->>'id')::bigint;
    select match_id into mid from public.match_comments where id=rid;
    if mid is null then raise exception 'Kommentaren finnes ikke.'; end if;
    perform public.require_editable_match(u,mid);
    delete from public.match_comments where id=rid;
    return '{"ok":true}'::jsonb;
  end if;

  raise exception 'Ukjent handling.';
end $$;

revoke all on function public.recompute_match_score(bigint) from public,anon,authenticated;
revoke all on function public.match_enhancements_snapshot(bigint) from public,anon;
revoke all on function public.match_enhancement_action(jsonb) from public,anon;
grant execute on function public.match_enhancements_snapshot(bigint) to authenticated;
grant execute on function public.match_enhancement_action(jsonb) to authenticated;

commit;
